#!/bin/sh
#ipe-rw script for IPE2 by NutCom Services, Inc. 2013.
#This software is GPLv2 licensed!
#See http://nutcom.hu/ipe2/

echo Remounting rootFS for R/W! Use \"ipe-ro\" to lock it again!
mount / -o remount,rw
